In [118]:
import numpy as np
import pandas as pd

In [119]:
df = pd.read_csv('/content/drive/MyDrive/health_insurance_dataset.csv')
df

Age  Annual_Income_Lakhs  Buy_Insurance
0     44                 8.05              0
1     38                 9.21              0
2     46                17.70              1
3     55                16.53              1
4     37                12.06              0
..   ...                  ...            ...
295   33                 9.44              0
296   48                10.64              0
297   43                 7.47              0
298   48                 9.76              0
299   46                14.71              1

[300 rows x 3 columns]

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  300 non-null    int64  
 1   Annual_Income_Lakhs  300 non-null    float64
 2   Buy_Insurance        300 non-null    int64  
dtypes: float64(1), int64(2)
memory usage: 7.2 KB


In [121]:
df.isnull().sum()

Age                    0
Annual_Income_Lakhs    0
Buy_Insurance          0
dtype: int64

In [122]:
df.duplicated().sum()

np.int64(0)

In [123]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('Buy_Insurance', axis=1).values, df['Buy_Insurance'].values, test_size=0.2, random_state=42)

In [124]:
X_train

array([[40.  , 11.79],
       [49.  ,  8.06],
       [55.  , 23.08],
       [47.  ,  5.98],
       [43.  , 24.13],
       [33.  , 12.11],
       [40.  ,  8.09],
       [52.  ,  9.55],
       [31.  , 12.07],
       [44.  ,  8.82],
       [42.  , 12.94],
       [30.  ,  7.52],
       [32.  , 16.77],
       [27.  ,  7.92],
       [34.  ,  5.06],
       [55.  , 16.72],
       [54.  ,  4.21],
       [31.  ,  8.33],
       [39.  , 13.63],
       [42.  , 18.45],
       [31.  , 13.56],
       [42.  ,  9.35],
       [25.  , 11.42],
       [45.  , 16.82],
       [20.  ,  8.13],
       [38.  , 14.38],
       [51.  , 21.97],
       [39.  , 25.17],
       [34.  , 12.31],
       [35.  , 10.93],
       [41.  , 26.09],
       [35.  ,  9.03],
       [43.  , 12.79],
       [35.  ,  8.32],
       [20.  , 10.37],
       [29.  , 17.13],
       [65.  , 21.32],
       [26.  ,  7.61],
       [30.  , 18.44],
       [50.  , 12.26],
       [32.  , 13.87],
       [33.  ,  8.28],
       [58.  ,  7.78],
       [44.

In [125]:
X_test

array([[50.  , 16.14],
       [56.  ,  4.4 ],
       [33.  ,  7.44],
       [45.  , 11.01],
       [33.  ,  6.65],
       [40.  ,  5.4 ],
       [31.  ,  7.25],
       [39.  , 15.76],
       [37.  , 12.92],
       [48.  , 10.76],
       [41.  , 10.05],
       [36.  , 10.55],
       [35.  , 12.8 ],
       [32.  , 13.68],
       [29.  ,  5.46],
       [21.  , 15.99],
       [33.  ,  7.94],
       [51.  , 11.88],
       [45.  ,  9.42],
       [44.  , 10.91],
       [40.  , 30.  ],
       [64.  , 23.08],
       [44.  ,  9.01],
       [27.  , 12.72],
       [38.  ,  9.73],
       [38.  , 13.77],
       [46.  ,  9.9 ],
       [33.  ,  9.44],
       [44.  ,  7.26],
       [33.  , 20.15],
       [43.  , 10.43],
       [49.  , 11.52],
       [29.  ,  8.68],
       [34.  ,  7.37],
       [47.  , 17.77],
       [47.  , 12.6 ],
       [47.  ,  9.06],
       [40.  ,  7.77],
       [35.  ,  5.91],
       [55.  , 19.68],
       [36.  , 30.  ],
       [40.  , 18.84],
       [38.  ,  9.68],
       [35.

In [126]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [127]:
X_train_scaled

array([[ 8.82324715e-02, -3.11950712e-01],
       [ 1.00449275e+00, -8.94758705e-01],
       [ 1.61533294e+00,  1.45209814e+00],
       [ 8.00879356e-01, -1.21975619e+00],
       [ 3.93652565e-01,  1.61615938e+00],
       [-6.24414413e-01, -2.61951099e-01],
       [ 8.82324715e-02, -8.90071241e-01],
       [ 1.30991285e+00, -6.61948005e-01],
       [-8.28027809e-01, -2.68201051e-01],
       [ 4.95459263e-01, -7.76009623e-01],
       [ 2.91845867e-01, -1.32264602e-01],
       [-9.29834507e-01, -9.79133052e-01],
       [-7.26221111e-01,  4.66168270e-01],
       [-1.23525460e+00, -9.16633536e-01],
       [-5.22607716e-01, -1.36350508e+00],
       [ 1.61533294e+00,  4.58355830e-01],
       [ 1.51352624e+00, -1.49631655e+00],
       [-8.28027809e-01, -8.52571531e-01],
       [-1.35742264e-02, -2.44529359e-02],
       [ 2.91845867e-01,  7.28666239e-01],
       [-8.28027809e-01, -3.53903513e-02],
       [ 2.91845867e-01, -6.93197764e-01],
       [-1.43886800e+00, -3.69762765e-01],
       [ 5.

In [128]:
X_test_scaled

array([[ 1.10629945,  0.36773153],
       [ 1.71713964, -1.46662928],
       [-0.62441441, -0.99163296],
       [ 0.59726596, -0.43382477],
       [-0.62441441, -1.1150695 ],
       [ 0.08823247, -1.31038049],
       [-0.82802781, -1.02132023],
       [-0.01357423,  0.30835699],
       [-0.21718762, -0.13538958],
       [ 0.90268605, -0.47288697],
       [ 0.19003917, -0.58382361],
       [-0.31899432, -0.50569921],
       [-0.42080102, -0.15413943],
       [-0.72622111, -0.0166405 ],
       [-1.0316412 , -1.30100556],
       [-1.84609479,  0.34429421],
       [-0.62441441, -0.91350856],
       [ 1.20810615, -0.29788832],
       [ 0.59726596, -0.68226035],
       [ 0.49545926, -0.44944965],
       [ 0.08823247,  2.53333978],
       [ 2.53159322,  1.45209814],
       [ 0.49545926, -0.74632235],
       [-1.2352546 , -0.16663934],
       [-0.11538092, -0.63382322],
       [-0.11538092, -0.00257811],
       [ 0.69907266, -0.60726093],
       [-0.62441441, -0.67913537],
       [ 0.49545926,

In [167]:
class ANN:
  def __init__(self, epochs=2000, learning_rate=0.01, loss='binary_crossentropy', activation='sigmoid'):
    self.epochs = epochs
    self.learning_rate = learning_rate
    self.loss = loss
    self.parameters = None
    self.activation = activation

  def sigmoid(self, Z):
    return 1 / (1+np.exp(-Z))

  def initialize_parameters(self, layer_dim):
    parameters = {}

    for i in range(1, len(layer_dim)):
      parameters['W'+str(i-1)] = np.ones((layer_dim[i-1], layer_dim[i])) * 0.001
      parameters['b'+str(i-1)] = np.zeros((layer_dim[i], 1))

    return parameters

  def forward_propagation(self, x, layer_dim):
    ## previous layer activation, current layer activation
    A_prev, A_curr = x, x

    for i in range(len(layer_dim)-1):
      A_prev = A_curr
      W = self.parameters['W'+str(i)]
      b = self.parameters['b'+str(i)]

      Z = np.dot(W.T, A_prev) + b
      A_curr = self.sigmoid(Z)

    return A_prev, A_curr

  def binary_crossentropy(self, y_true, y_pred):
    epsilon = 1e-9
    return -(y_true*np.log(y_pred+epsilon) + (1-y_true)*np.log(1-y_pred+epsilon))

  def update_parameters(self, parameters, A_prev, A_curr, y, x):
    y_predict = A_curr[0][0]

    parameters['W1'][0][0] += self.learning_rate * (y-y_predict) * (A_prev[0][0])
    parameters['W1'][1][0] += self.learning_rate * (y-y_predict) * (A_prev[1][0])
    parameters['b1'][0][0] += self.learning_rate * (y-y_predict)

    parameters['W0'][0][0] += self.learning_rate * (y-y_predict) * (parameters['W1'][0][0]) * (A_prev[0][0]) * (1-(A_prev[0][0])) * x[0][0]
    parameters['W0'][1][0] += self.learning_rate * (y-y_predict) * (parameters['W1'][0][0]) * (A_prev[0][0]) * (1-(A_prev[0][0])) * x[1][0]
    parameters['b0'][0][0] += self.learning_rate * (y-y_predict) * (parameters['W1'][0][0]) * (A_prev[0][0]) * (1-(A_prev[0][0]))

    parameters['W0'][0][1] += self.learning_rate * (y-y_predict) * (parameters['W1'][1][0]) * (A_prev[1][0]) * (1- (A_prev[1][0])) * x[0][0]
    parameters['W0'][1][1] += self.learning_rate * (y-y_predict) * (parameters['W1'][1][0]) * (A_prev[1][0]) * (1- (A_prev[1][0])) * x[1][0]
    parameters['b0'][1][0] += self.learning_rate * (y-y_predict) * (parameters['W1'][1][0]) * (A_prev[1][0]) * (1- (A_prev[1][0]))

    return parameters

  def fit(self, X_train, y_train):
    ## we are implementing a simple neural network of 1 input layer of 2 nodes,
    ## 1 hidden layer of 2 nodes and 1 output layer of 1 node and activation function of all nodes is linear
    self.layer_dim = [2, 2, 1]

    ## initialize parameters i.e assign values to weights as 1 and bias as 0
    self.parameters = self.initialize_parameters(self.layer_dim)

    ## running a loop epochs number of times
    for i in range(self.epochs):
      ## creating empty list to store loss at each epoch
      Loss = []

      ## pick a data point from X_train
      for idx in range(len(X_train)):
        x = X_train[idx]
        y = y_train[idx]

        ## make prediction of that data point using forward propagation
        A_prev, A_curr = self.forward_propagation(x, self.layer_dim)
        y_predict = A_curr[0][0]

        ## calculate loss
        loss = self.binary_crossentropy(y, y_predict)

        ## update parameters
        self.parameters = self.update_parameters(self.parameters, A_prev, A_curr, y, x.reshape(2, 1))

        Loss.append(loss)

      # print(f"Epoch {i+1} : {np.mean(Loss)}")

  def predict(self, X_test):
    y_prob = np.zeros((X_test.shape[0], 2))

    for idx in range(X_test.shape[0]):
      x = X_test[idx]
      A_prev, A_curr = self.forward_propagation(x, self.layer_dim)
      y_prob[idx][0] = A_curr[0][0] ## probability of class to be 1
      y_prob[idx][1] = 1 - A_curr[0][0] ## probability of class to be 0

    print(y_prob)
    return np.where(y_prob[:, 0] > 0.5, 1, 0)

In [168]:
ann1 = ANN()

In [169]:
ann1.fit(X_train_scaled, y_train)

In [170]:
y_pred = ann1.predict(X_test_scaled)
y_pred

[[9.99689317e-01 3.10682578e-04]
 [8.11602857e-06 9.99991884e-01]
 [8.08877789e-06 9.99991911e-01]
 [9.48150180e-06 9.99990518e-01]
 [8.08873624e-06 9.99991911e-01]
 [8.08880777e-06 9.99991911e-01]
 [8.08873434e-06 9.99991911e-01]
 [7.69232505e-04 9.99230767e-01]
 [8.58504978e-06 9.99991415e-01]
 [1.22857956e-05 9.99987714e-01]
 [8.15338663e-06 9.99991847e-01]
 [8.10275060e-06 9.99991897e-01]
 [8.26304400e-06 9.99991737e-01]
 [8.23774626e-06 9.99991762e-01]
 [8.08871411e-06 9.99991911e-01]
 [8.11392185e-06 9.99991886e-01]
 [8.08883764e-06 9.99991911e-01]
 [1.33399965e-03 9.98666000e-01]
 [8.25166235e-06 9.99991748e-01]
 [8.85434106e-06 9.99991146e-01]
 [9.99778994e-01 2.21006249e-04]
 [9.99778994e-01 2.21006190e-04]
 [8.14996831e-06 9.99991850e-01]
 [8.09346996e-06 9.99991907e-01]
 [8.10018213e-06 9.99991900e-01]
 [1.06730262e-05 9.99989327e-01]
 [8.56930740e-06 9.99991431e-01]
 [8.08959996e-06 9.99991910e-01]
 [8.09488772e-06 9.99991905e-01]
 [9.96991918e-01 3.00808224e-03]
 [8.345773

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [174]:
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [173]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, y_pred)*100)

100.0


In [172]:
print(confusion_matrix(y_test, y_pred))

[[51  0]
 [ 0  9]]
